export const categories = {
  locations: [
    "Airplane",
    "Beach",
    "Bank",
    "Cathedral",
    "Casino",
    "Corporate Party",
    "Cemetery",
    "Circus Tent",
    "Crusader Army",
    "Day Spa",
    "Embassy",
    "Forest",
    "Hospital",
    "Hotel",
    "Military Base",
    "Movie Studio",
    "Laboratory",
    "Ocean Liner",
    "Passenger Train",
    "Polar Station",
    "Pirate Ship",
    "Police Station",
    "Park",
    "Restaurant",
    "Service Station",
    "School",
    "Space Station",
    "Supermarket",
    "Submarine",
    "University",
    "Theatre",
    "Train Station",
    "Warehouse",
    "WW2 Squad",
  ],
  monsters: [
    "Alien",
    "Bigfoot",
    "Blob",
    "Cthulhu",
    "Demon",
    "Ghost",
    "Goblin",
    "Mummy",
    "Phantom",
    "Pirate",
    "Robot",
    "Skeleton",
    "Vampire",
    "Werewolf",
    "Witch",
    "Zombie",
    "Dragon",
    "Troll",
    "Giant",
    "Kraken",
    "Cyclops",
    "Harpy",
    "Minotaur",
  ],
  animals: [
    "Bat",
    "Owl",
    "Rat",
    "Spider",
    "Raven",
    "Snake",
    "Toad",
    "Wolf",
    "Crow",
    "Fox",
    "Hawk",
    "Lizard",
    "Scorpion",
    "Coyote",
    "Jackal",
    "Hyena",
    "Vulture",
    "Piranha",
    "Alligator",
    "Cow",
    "Pig",
    "Goat",
    "Chicken",
    "Horse",
    "Dog",
    "Cat",
    "Mouse",
    "Deer",
    "Elephant",
    "Tiger",
    "Lion",
    "Bear",
    "Rabbit",
    "Squirrel",
    "Frog",
    "Butterfly",
    "Bee",
    "Ant",
  ],
  halloweenObjects: [
    "Amulet",
    "Broomstick",
    "Cauldron",
    "Candle",
    "Crystal Ball",
    "Gravestone",
    "Jack-o'-lantern",
    "Magic Wand",
    "Potion",
    "Scythe",
    "Spellbook",
    "Tarot Cards",
    "Wand",
    "Witch Hat",
    "Skull",
    "Lantern",
    "Chains",
    "Coffin",
    "Mask",
    "Mirror",
    "Rope",
    "Torch",
  ],
  foods: [
    "Apple",
    "Bread",
    "Cheese",
    "Chocolate",
    "Doughnut",
    "Egg",
    "Fish",
    "Grapes",
    "Hamburger",
    "Ice Cream",
    "Juice",
    "Kiwi",
    "Lemon",
    "Mango",
    "Noodles",
    "Orange",
    "Pineapple",
    "Pizza",
    "Rice",
    "Salad",
    "Steak",
    "Tomato",
    "Watermelon",
    "Yogurt",
  ],
  transportation: [
    "Bicycle",
    "Boat",
    "Bus",
    "Car",
    "Helicopter",
    "Motorcycle",
    "Scooter",
    "Skateboard",
    "Subway",
    "Taxi",
    "Train",
    "Truck",
    "Van",
    "Airplane",
    "Hot Air Balloon",
    "Rocket",
    "Spaceship",
  ],
};
